# Generated by Django 5.0.6 on 2024-06-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='course_lctures', to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecturematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lecturematerial',
            name='type',
            field=models.CharField(choices=[('Text', 'Text'), ('Video', 'Video'), ('Image', 'Image')], max_length=10),
        ),
    ]
