# Generated by Django 5.0.6 on 2024-06-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_lecture_course_lecture_order_lecturematerial_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturematerial',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
