# Generated by Django 5.0.3 on 2024-07-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_courseprofile_delete_courseuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseProfile',
        ),
    ]
