# Generated by Django 5.0.3 on 2024-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('Open', 'Активная'), ('Submitted', 'Был оформлен заказ')], default='Open', max_length=15),
        ),
    ]
