# Generated by Django 5.0.3 on 2024-06-18 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_alter_basket_status'),
        ('course', '0006_alter_lecture_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bsket_lines', to='basket.basket'),
        ),
        migrations.AlterField(
            model_name='line',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lines', to='course.course'),
        ),
    ]
